// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuitionManagementSystem.Web.Infrastructure.Persistence;

#nullable disable

namespace TuitionManagementSystem.Web.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201141639_AddBasicDomains")]
    partial class AddBasicDomains
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakenOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PreferredClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreferredClassroomId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int?>("Repeat")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RepeatUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasDiscriminator().HasValue("PaymentMethod");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessRole")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastChanged")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.BankPaymentMethod", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Payment.PaymentMethod");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("BankPaymentMethod");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.CardPaymentMethod", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Payment.PaymentMethod");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CardPaymentMethod");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.GenericPaymentMethod", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Payment.PaymentMethod");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("GenericPaymentMethod");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Parent", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.User.User");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("FamilyId");

                    b.ToTable("User", t =>
                        {
                            t.Property("FamilyId")
                                .HasColumnName("Parent_FamilyId");
                        });

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Student", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.User.User");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("FamilyId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Teacher", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.User.User");

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.HasIndex("ClassId");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Attendance", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Class", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Classroom", "PreferredClassroom")
                        .WithMany()
                        .HasForeignKey("PreferredClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredClassroom");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Enrollment", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Schedule", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Classroom", null)
                        .WithMany("Schedules")
                        .HasForeignKey("ClassroomId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Session", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Class", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Classroom", null)
                        .WithMany("SessionsHeld")
                        .HasForeignKey("ClassroomId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Invoice", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Payment.Payment", "Payment")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentId");

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany("Invoices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Payment", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Payment.PaymentMethod", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Account", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Parent", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Family", "Family")
                        .WithMany("Parents")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Student", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Family", "Family")
                        .WithMany("Children")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Teacher", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Class", null)
                        .WithMany("TeachersInCharge")
                        .HasForeignKey("ClassId");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Class", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Sessions");

                    b.Navigation("TeachersInCharge");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Classroom", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("SessionsHeld");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Subject", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Payment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Family", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
