// <auto-generated />

#nullable disable

namespace TuitionManagementSystem.Web.Infrastructure.Persistence.Migrations
{
    using System.Net;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.EntityFrameworkCore.Migrations;

    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214094653_AddSubjectDeletedAt")]
    partial class AddSubjectDeletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RelatedSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RelatedSessionId");

                    b.ToTable("Announcements");

                    b.HasDiscriminator().HasValue("Announcement");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.AnnouncementFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("FileId");

                    b.ToTable("AnnouncementFiles");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.SubmissionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakenOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.AttendanceCode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AttendanceCodes");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PreferredClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreferredClassroomId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.CourseTeacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("CourseTeachers");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<DateTime[]>("ExceptionDates")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.PrimitiveCollection<DateTime[]>("RecurrenceDates")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.ScheduleRecurrencePattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<int[]>("ByDay")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByHour")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByMinute")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByMonth")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByMonthDay")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("BySecond")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("BySetPosition")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByWeekNo")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("ByYearDay")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyType")
                        .HasColumnType("integer");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Until")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleRecurrencePatterns");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CodeGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CodeId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("CodeId");

                    b.HasIndex("CourseId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Notification.FamilyInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("UserId");

                    b.ToTable("FamilyInvites");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Notification.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasDiscriminator().HasValue("Notification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoicedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MethodId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasDiscriminator().HasValue("PaymentMethod");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessRole")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastChanged")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProfileImageId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProfileImageId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.AccountSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<IPAddress>("LastIp")
                        .HasColumnType("inet");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("AccountSessions");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Assignment", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Class.Announcement.Announcement");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Assignment");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Material", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Class.Announcement.Announcement");

                    b.HasDiscriminator().HasValue("Material");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Notification.FamilyInviteNotification", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Notification.Notification");

                    b.Property<int>("FamilyInviteId")
                        .HasColumnType("integer");

                    b.HasIndex("FamilyInviteId");

                    b.HasDiscriminator().HasValue("FamilyInviteNotification");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.BankPaymentMethod", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Payment.PaymentMethod");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("BankPaymentMethod");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.CardPaymentMethod", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Payment.PaymentMethod");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("CardPaymentMethod");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.GenericPaymentMethod", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.Payment.PaymentMethod");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("GenericPaymentMethod");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Parent", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.User.User");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("FamilyId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("FamilyId")
                                .HasColumnName("Parent_FamilyId");
                        });

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Student", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.User.User");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("FamilyId");

                    b.ToTable("Users", t =>
                        {
                            t.Property("FamilyId")
                                .HasColumnName("Student_FamilyId");
                        });

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Teacher", b =>
                {
                    b.HasBaseType("TuitionManagementSystem.Web.Models.User.User");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.HasIndex("FamilyId");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Announcement", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Course", "Course")
                        .WithMany("Announcements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Teacher", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Session", "RelatedSession")
                        .WithMany()
                        .HasForeignKey("RelatedSessionId");

                    b.Navigation("Course");

                    b.Navigation("CreatedBy");

                    b.Navigation("RelatedSession");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.AnnouncementFile", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Announcement.Announcement", "Announcement")
                        .WithMany("Attachments")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("File");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Submission", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Announcement.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.SubmissionFile", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Announcement.Submission", "Submission")
                        .WithMany("Attachments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Attendance", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Course", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Classroom", "PreferredClassroom")
                        .WithMany()
                        .HasForeignKey("PreferredClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredClassroom");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.CourseTeacher", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Course", "Course")
                        .WithMany("TeachersInCharge")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Enrollment", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Schedule", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Classroom", null)
                        .WithMany("Schedules")
                        .HasForeignKey("ClassroomId");

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Course", "Course")
                        .WithOne("Schedule")
                        .HasForeignKey("TuitionManagementSystem.Web.Models.Class.Schedule", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.ScheduleRecurrencePattern", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Schedule", "Schedule")
                        .WithMany("RecurrencePatterns")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Session", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Classroom", "Classroom")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.AttendanceCode", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId");

                    b.HasOne("TuitionManagementSystem.Web.Models.Class.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Code");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.File", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.User", "CreatedBy")
                        .WithMany("Files")
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Notification.FamilyInvite", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Parent", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagementSystem.Web.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Requester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Notification.Notification", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Invoice", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Payment.Payment", "Payment")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentId");

                    b.HasOne("TuitionManagementSystem.Web.Models.User.Student", "Student")
                        .WithMany("Invoices")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Payment", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Payment.PaymentMethod", "Method")
                        .WithOne("Payment")
                        .HasForeignKey("TuitionManagementSystem.Web.Models.Payment.Payment", "MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Account", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.File", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageId");

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.AccountSession", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.User", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("TuitionManagementSystem.Web.Models.User.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Notification.FamilyInviteNotification", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.Notification.FamilyInvite", "FamilyInvite")
                        .WithMany()
                        .HasForeignKey("FamilyInviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyInvite");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Parent", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Family", "Family")
                        .WithMany("Parents")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Student", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Family", "Family")
                        .WithMany("Children")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Teacher", b =>
                {
                    b.HasOne("TuitionManagementSystem.Web.Models.User.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Announcement", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Announcement.Submission", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Classroom", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Course", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Enrollments");

                    b.Navigation("Schedule");

                    b.Navigation("Sessions");

                    b.Navigation("TeachersInCharge");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Schedule", b =>
                {
                    b.Navigation("RecurrencePatterns");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Class.Subject", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.Payment", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.Payment.PaymentMethod", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Account", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Family", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.User", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TuitionManagementSystem.Web.Models.User.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
